### ISSUE TITLE
Why cannot I install EvoBinoSDK?

### ISSUE THREAD

**Issue by MukaiyamaTakashi** [ShanghaiEyevolutionTechnology/EvoBinoSDK-samples#1]
I tried to install EvoBinoSDK 0.7.1. But I cannot install it.
I have already installed following items:
 Ubuntu 16.04
 CUDA 8.0, 9.0, 9.1

When I execute EvoBinoSDK installer, EvoBinoSDK display following error.

> Do you accept the license? [yN]: 
y
Finding CUDA Libraries in system...
Found CUDA 8.0
9.0
9.1
Could Not found Cuda 8.0. Exiting...

Why cannot I install EvoBinoSDK?

**Comment by ShanghaiEyevolutionTechnology** [comment]
SDK 0.7.1 ONLY supports CUDA 8.0 now.
Please make sure that CUDA path in LD_LIBRARY_PATH only has 8.0.
Then re-install SDK again.
This should works.
